apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
resources:
  - namespace.yml
  - configmap.yml
  - secrets.yml
  - storage.yml
  - deployment.yml
  - networking.yml
