apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-container-env
  namespace: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-unesty-kube-prod
    kind: ClusterSecretStore
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: /databases/pgadmin/email
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: /databases/pgadmin/password
