apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ingressroute-certificate
  namespace: argocd
spec:
  secretName: argocd-cert-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - argo.kube.llama.onl
