apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld1-ingressroute-certificate
  namespace: default
spec:
  secretName: helloworld1-cert-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - helloworld1.kube.llama.onl
