apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-external-secrets
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-unesty-kube-prod
  target:
    name: minio-secret
  refreshPolicy: Periodic
  refreshInterval: 5m
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /minio/longhorn/minio-longhorn-backup-access-key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /minio/longhorn/minio-longhorn-backup-secret-key
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: /minio/minio-endpoint
