apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-unesty-kube-prod
  namespace: external-secrets
spec:
  provider:
    infisical:
      hostAPI: https://infisical.llama.onl
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-universal-auth
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-universal-auth
      secretsScope:
        projectSlug: unesty-kube-secrets
        environmentSlug: prod
