apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-external-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-unesty-kube-prod
  target:
    name: cloudflare-api-token-secret
  refreshPolicy: Periodic
  refreshInterval: 5m
  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare-api-token
