apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-database
  namespace: vaultwarden
spec:
  description: "Database for vaultwarden"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3

  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: vaultwarden-db-creds

  storage:
    size: 1Gi
    storageClass: local-path

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
