apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-db-creds-external-secret
  namespace: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-unesty-kube-prod
  target:
    name: vaultwarden-db-creds
  refreshPolicy: Periodic
  refreshInterval: 5m
  data:
    - secretKey: username
      remoteRef:
        key: /databases/vaultwarden/user
    - secretKey: password
      remoteRef:
        key: /databases/vaultwarden/password
